package com.bueno.kitchen.managers.payment;

import android.content.ActivityNotFoundException;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.util.Base64;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;

import com.bueno.kitchen.activities.OLAWebViewActivity;
import com.bueno.kitchen.managers.payment.core.PaymentManager;
import com.bueno.kitchen.models.core.PaymentDetailModel;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * Created by samir on 26/09/16.
 */
public class OlaMoneyPayManager extends PaymentManager {

    WebView webView;
    Context context ;
    public  OlaMoneyPayManager(Context context){
        this.context  = context ;
    }


    @Override
    public void makePayment(PaymentDetailModel paymentDetailModel) {

        invokeOlaMoney(""+OLAWebViewActivity.bill , "9898656532");
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {

        Toast.makeText(context, "sending to payment manager "+data, Toast.LENGTH_SHORT).show();
        paymentCallback.onSuccess(data.toString());

    }





    /*
  bill - JSON bill generated by merchant server
  phoneNumber - Users phone number. Can be null
*/
    public void invokeOlaMoney(String bill, String phoneNumber) {
        Toast.makeText(context, "ola exsist in mobile " +check_olacabs(), Toast.LENGTH_SHORT).show();
        try {
            Toast.makeText(context, "inside OlaMoney TRY", Toast.LENGTH_SHORT).show();
//            Intent intent = new Intent("com.olacabs.olamoney.pay");
//
//            intent.setFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);
//            intent.putExtra("bill", bill);
//            intent.setPackage("com.test.olacabs");
            context.startActivity(new Intent("com.olacabs.olamoney.pay").putExtra("bill", bill).setFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS).setPackage("com.olacabs.customer"));//Remember to change this to "com.olacabs.customer" before you go live
            //context.startActivity(intent);
        } catch(ActivityNotFoundException e) {
    /*Activity not found exception - route the flow through webview*/
            Toast.makeText(context, "inside OlaMoney CATCH", Toast.LENGTH_SHORT).show();
            invokeOlaMoneyWebViewFlow(OLAWebViewActivity.bill, phoneNumber);
        }
    }

/*
  bill - JSON bill generated by merchant server
  phoneNumber - Users phone number. Can be null
*/



    public void invokeOlaMoneyWebViewFlow(String bill, String phoneNumber) {
        context.startActivity(new Intent(context , OLAWebViewActivity.class));
        StringBuffer buffer=new   StringBuffer("http://sandbox.olamoney.in/olamoney/webview/index.html");
        //Change http://sandbox.olamoney.in to https://om.olacabs.com before you go live
        String base64_bill = Base64.encodeToString(bill.getBytes(), Base64.DEFAULT);
        buffer.append("?bill="+base64_bill);
        buffer.append("&phone="+ URLEncoder.encode(phoneNumber == null ? "" : phoneNumber));
        webView.getSettings().setJavaScriptEnabled(true);
        webView.setWebViewClient(new WebViewClient());
        webView.loadUrl(buffer.toString());
    }



    private boolean check_olacabs() {

        PackageManager pm = context.getPackageManager();

        try {
            pm.getPackageInfo("com.olacabs.customer", PackageManager.GET_ACTIVITIES);
            return true;
        } catch (PackageManager.NameNotFoundException e) {
            return false;
        }


    }






    public String get_SHA_512_hash(String passwordToHash, String   salt) throws UnsupportedEncodingException {
        String generatedhash = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            md.update(salt.getBytes("UTF-8"));
            byte[] bytes = md.digest(passwordToHash.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder();
            for(int i=0; i< bytes.length ;i++){
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            generatedhash = sb.toString();
        }
        catch (NoSuchAlgorithmException e){
            e.printStackTrace();
        }
        return generatedhash;
    }









    //  response after ola payment
//    {
//        "type":"debit",
//            "status":"success",
//            "transactionId":"bgi9-g8pf-v3jz",
//            "merchantBillId":"JLhq2ZxZX",
//            "amount":"50.00",
//            "hash":"5c8216201632af4811457f1bd6206da13ed128dedabab6f9b82b2992bc96b784d89463fd442825c79c8fc5d298118361bd85ec1213",
//            "timestamp":1439995769451,
//            "comments":"test",
//            "udf":"test"
//        "isCashbackAttempted":"true" (This will be returned only couponCode is passed)
//        "isCashbackSuccessful":"true" (This will be returned only couponCode is passed)
//    }







}
