package com.bueno.kitchen.managers.payment;

import android.content.ActivityNotFoundException;
import android.content.Context;
import android.content.Intent;
import android.util.Base64;
import android.webkit.WebView;
import android.webkit.WebViewClient;

import com.bueno.kitchen.managers.payment.core.PaymentManager;
import com.bueno.kitchen.models.core.PaymentDetailModel;

import java.net.URLEncoder;

/**
 * Created by samir on 26/09/16.
 */
public class OlaMoneyPayManager extends PaymentManager {

    WebView webView;
    Context context ;
    public  OlaMoneyPayManager(Context context){
        this.context  = context ;
    }


    @Override
    public void makePayment(PaymentDetailModel paymentDetailModel) {

        invokeOlaMoney("88" , "9898656532");
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {

    }





    /*
  bill - JSON bill generated by merchant server
  phoneNumber - Users phone number. Can be null
*/
    public void invokeOlaMoney(String bill, String phoneNumber) {
        try {
            Intent intent = new Intent("com.olacabs.olamoney.pay");
            intent.setFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);
            intent.putExtra("bill", bill);
            intent.setPackage("com.test.olacabs"); //Remember to change this to "com.olacabs.customer" before you go live
            context.startActivity(intent);
        } catch(ActivityNotFoundException e) {
    /*Activity not found exception - route the flow through webview*/
            invokeOlaMoneyWebViewFlow(bill, phoneNumber);
        }
    }

/*
  bill - JSON bill generated by merchant server
  phoneNumber - Users phone number. Can be null
*/
    public void invokeOlaMoneyWebViewFlow(String bill, String phoneNumber) {
        StringBuffer buffer=new   StringBuffer("http://sandbox.olamoney.in/olamoney/webview/index.html");
        //Change http://sandbox.olamoney.in to https://om.olacabs.com before you go live
        String base64_bill = Base64.encodeToString(bill.getBytes(), Base64.DEFAULT);
        buffer.append("?bill="+base64_bill);
        buffer.append("&phone="+ URLEncoder.encode(phoneNumber == null ? "" : phoneNumber));
        webView.getSettings().setJavaScriptEnabled(true);
        webView.setWebViewClient(new WebViewClient());
        webView.loadUrl(buffer.toString());
    }





}
